version: '3.7'
services:
  web:
    build: .
    command: gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db
      - cache
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - 5432:5432
  cache:
    image: redis:latest
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
  celery:
    build: .
    command: celery -A config worker -B
    links:
      - cache
    depends_on:
      - web
      - cache
volumes:
  postgres_data: